Repository SWE574-G3/SWE-574-G3, pull requests merged in 2024-10, with the labels that each got.

#46 32 bugfrontend runtime error on attempting a post without a chosen template
  .gitignore
  Communitter/src/main/java/com/communitter/api/auth/authconfig/FilterConfig.java
  communitter-frontend/Frontend.Dockerfile
  communitter-frontend/src/components/AdvancedSearch.js
  communitter-frontend/src/components/Filters.js
  communitter-frontend/src/components/postModal.js
Labels: bug, Frontend

#60 [DEV][BACKEND] Issue 55: Sending Invitation
  Communitter/src/main/java/com/communitter/api/controller/InvitationController.java
  Communitter/src/main/java/com/communitter/api/dto/InvitationDto.java
  Communitter/src/main/java/com/communitter/api/dto/request/InvitationCreateRequestDto.java
  Communitter/src/main/java/com/communitter/api/model/Invitation.java
  Communitter/src/main/java/com/communitter/api/repository/InvitationRepository.java
  Communitter/src/main/java/com/communitter/api/service/InvitationService.java
  Communitter/src/main/java/com/communitter/api/util/InvitationStatus.java
  Communitter/src/main/resources/application-local.properties
  Communitter/src/main/resources/data.sql
Labels: enhancement, Backend, ready for review

#63 [DEV][BACKEND] Comment Backend
  Communitter/src/main/java/com/communitter/api/controller/CommentController.java
  Communitter/src/main/java/com/communitter/api/controller/UserController.java
  Communitter/src/main/java/com/communitter/api/dto/CommentDto.java
  Communitter/src/main/java/com/communitter/api/model/Comment.java
  Communitter/src/main/java/com/communitter/api/model/Post.java
  Communitter/src/main/java/com/communitter/api/repository/CommentRepository.java
  Communitter/src/main/java/com/communitter/api/service/CommentService.java
Labels: enhancement, Backend
