Repository SWE574-G3/SWE-574-G3, pull requests merged in 2024-11, with the labels that each got.

#74 [DEV][BACKEND] Issue 67: List invitations in community
  Communitter/pom.xml
  Communitter/src/main/java/com/communitter/api/controller/InvitationController.java
  Communitter/src/main/java/com/communitter/api/dto/CommunityDto.java
  Communitter/src/main/java/com/communitter/api/dto/InvitationDto.java
  Communitter/src/main/java/com/communitter/api/dto/RoleDto.java
  Communitter/src/main/java/com/communitter/api/dto/UserDto.java
  Communitter/src/main/java/com/communitter/api/mapper/CommunityMapper.java
  Communitter/src/main/java/com/communitter/api/mapper/InvitationMapper.java
  Communitter/src/main/java/com/communitter/api/mapper/RoleMapper.java
  Communitter/src/main/java/com/communitter/api/mapper/UserMapper.java
  Communitter/src/main/java/com/communitter/api/model/Invitation.java
  Communitter/src/main/java/com/communitter/api/model/User.java
  Communitter/src/main/java/com/communitter/api/repository/InvitationRepository.java
  Communitter/src/main/java/com/communitter/api/service/InvitationService.java
Labels: enhancement, Backend, ready for review

#73 [DEV][FRONTEND] Display: Upvote and Downvote on Posts #41
  communitter-frontend/package.json
  communitter-frontend/src/components/PostCard.js
  communitter-frontend/src/index.js
Labels: Frontend, ready for review

#83 Feature/#80/frontend post view
  Communitter/src/main/java/com/communitter/api/controller/PostController.java
  communitter-frontend/src/App.js
  communitter-frontend/src/components/CommentCard.js
  communitter-frontend/src/components/PostCard.js
  communitter-frontend/src/components/PostComments.js
  communitter-frontend/src/pages/postPage.js
  communitter-frontend/src/utilities/CommentService.js
Labels: Frontend, ready for review

#81 [DEV][BACKEND] Issue 75: List invitations for users
  Communitter/src/main/java/com/communitter/api/controller/InvitationController.java
  Communitter/src/main/java/com/communitter/api/service/InvitationService.java
  Communitter/src/test/java/com/communitter/api/service/InvitationServiceTest.java
Labels: enhancement, Backend, ready for review

#87 [SYNC] Sync main into dev
  report/m1_g3.md
Labels: ready for review

#88 [DEV][BACKEND] Issue 76: Accept, Reject or Cancel An Invitation
  Communitter/src/main/java/com/communitter/api/controller/CommunityController.java
  Communitter/src/main/java/com/communitter/api/controller/InvitationController.java
  Communitter/src/main/java/com/communitter/api/repository/InvitationRepository.java
  Communitter/src/main/java/com/communitter/api/service/CommunityService.java
  Communitter/src/main/java/com/communitter/api/service/InvitationService.java
  Communitter/src/test/java/com/communitter/api/service/InvitationServiceTest.java
Labels: enhancement, Backend, ready for review

#102 [DEV][BACKEND] Create default post template for every new community #101
  Communitter/src/main/java/com/communitter/api/model/DataField.java
  Communitter/src/main/java/com/communitter/api/repository/DataFieldTypeRepository.java
  Communitter/src/main/java/com/communitter/api/service/CommunityService.java
Labels: Backend, ready for review

#103 Feature/78/community recommendation service
  Communitter/src/main/java/com/communitter/api/controller/RecommendationController.java
  Communitter/src/main/java/com/communitter/api/dto/CommunityLabelDto.java
  Communitter/src/main/java/com/communitter/api/dto/UserInterestDto.java
  Communitter/src/main/java/com/communitter/api/model/Community.java
  Communitter/src/main/java/com/communitter/api/model/CommunityLabel.java
  Communitter/src/main/java/com/communitter/api/model/Post.java
  Communitter/src/main/java/com/communitter/api/model/User.java
  Communitter/src/main/java/com/communitter/api/model/UserInterest.java
  Communitter/src/main/java/com/communitter/api/model/WikiEntity.java
  Communitter/src/main/java/com/communitter/api/repository/CommunityLabelRepository.java
  Communitter/src/main/java/com/communitter/api/repository/UserInterestRepository.java
  Communitter/src/main/java/com/communitter/api/repository/WikiEntityRepository.java
  Communitter/src/main/java/com/communitter/api/service/RecommendationService.java
Labels: Backend, Recommendation System

#106 bug fixes for communityDto and default template
  Communitter/src/main/java/com/communitter/api/service/CommunityService.java
  Communitter/src/main/java/com/communitter/api/service/RecommendationService.java
  communitter-frontend/package-lock.json
  communitter-frontend/src/App.js
Labels: bug, Backend, Recommendation System

#108 [BUG][BACKEND] Template service does not allow two different communities to create templates with same name #107
  Communitter/src/main/java/com/communitter/api/model/Template.java
  Communitter/src/main/java/com/communitter/api/service/CommunityService.java
Labels: bug, Backend, ready for review

#109 [DEV][BACKEND] Feature/#71/comment edit delete
  Communitter/src/main/java/com/communitter/api/auth/CustomAuthorizer.java
  Communitter/src/main/java/com/communitter/api/controller/CommentController.java
  Communitter/src/main/java/com/communitter/api/service/CommentService.java
Labels: Backend

#116 Feature/#113/frontend delete edit
  communitter-frontend/src/components/CommentCard.js
  communitter-frontend/src/components/PostComments.js
  communitter-frontend/src/pages/postPage.js
  communitter-frontend/src/utilities/CommentService.js
Labels: Frontend, ready for review
